name 'CppUTest'
maintainer 'Martin Melik Merkumians'
maintainer_email 'mmm@acin.tuwien.ac.at'
license 'MIT'
description 'Installs/Configures CppUTest'
long_description 'Installs/Configures CppUTest'
version '0.1.0'

depends 'git', '~> 8.0.0'
depends 'libtool', '~> 0.1.0'
depends 'build-essential', '~> 8.0.4'
